---

- name: Activating a cockpit
  no_log: true # Not showing keys in logs
  uri:
    url: "{{ scw_observability_url }}/activate-cockpit"
    method: POST
    return_content: yes
    headers:
      X-Auth-Token: "{{ scw_api_key }}"
    body_format: json
    body:
      project_id: "{{ scw_project_id }}"
    status_code: 200, 409 # 200 is created, 409 is already exists; makes idempotent

- name: Getting cockpit info
  no_log: true # Not showing keys in logs
  uri:
    url: "{{ scw_observability_url }}/cockpit?project_id={{ scw_project_id }}"
    method: GET
    return_content: yes
    headers:
      X-Auth-Token: "{{ scw_api_key }}"
    status_code: 200
  register: activation_info_query

- debug:
    msg: "{{ activation_info_query.json }}"

- name: "Persist activation details"
  vars:
    role_variables:
      cockpit_grafana_url: "{{ activation_info_query.json['endpoints']['grafana_url'] }}"
      cockpit_grafana_username: "{{ activation_info_query.json['grafana_username'] }}"
      cockpit_grafana_password: "{{ activation_info_query.json['grafana_password'] }}"
      cockpit_logs_url: "{{ activation_info_query.json['endpoints']['logs_url'] }}"
      cockpit_metrics_url: "{{ activation_info_query.json['endpoints']['metrics_url'] }}"
      cockpit_alertmanager_url: "{{ activation_info_query.json['endpoints']['alertmanager_url'] }}"
  set_fact:
    scw_cockpit: "{{ scw_cockpit | default({}) | combine(role_variables) }}"

- debug:
    msg: "{{ hostvars['localhost']['scw_cockpit'] }}"
