logs:
  positions_directory: /tmp/positions/
  configs:
  - name: scw
    clients:
    - url: LOGS_PUSH_URL
      tenant_id: PUSH_TOKEN_ID
    scrape_configs:
    - job_name: logs
      static_configs:
      - targets: [localhost]
        labels:
          job: logs
          __path__: /logs/*
